### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by lord** [christiangenco/markdowntomla#2]
Would be nice to slap `license.md` on this project, if you have the chance!

**Comment by lord** [comment]
Also, thanks for this excellent project, it's been super helpful!

**Comment by christiangenco** [comment]
Huh. What should my license be?

Also - awesome! I'm glad you like it :D

**Comment by lord** [comment]
Many projects seem to choose MIT or Apache 2.0? Your call!

**Comment by christiangenco** [comment]
Done 😄
